server:
  port: 8080

# Configuración de eureka client
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Configuraciónn de routes
spring:
  cloud:
    gateway:
      routes:
        - id: moviesRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: movies
                statusCodes: 500
                fallbackUri: forward:/catalog/**
        - id: seriesRoute
          uri: lb://serie-service
          predicates:
            - Path=/series/**
          filters:
            - name: CircuitBreaker
              args:
                name: series
                statusCodes: 500
                fallbackUri: forward:/catalog/**
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**






