server:
  port: 8001
  servlet:
    context-path: /movies/

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Configuración de eureka client
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

message: Hello from movie-service

# Configuración de swagger
springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  show-actuator: true
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true

# Configuraciónn de actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, openapi, swagger-ui
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

# info properties
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: movie-service
  svc:
    port: ${server.port}