server:
  port: 8003
  servlet:
    context-path: /series/

# Configuración base de datos de persistencia MongoDB según consigna
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/series
    username: root
    password: root
    authentication-database: admin

# Configuración de eureka client
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
message: Hello from serie-service!!

# Configuración de swagger
spring-doc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  show-actuator: true
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true

# Configuraciónn de actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, openapi, swagger-ui
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

# info properties
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: serie-service
  svc:
    port: ${server.port}
